WEBUI/Areas/Anket/Controllers/DegerlendirmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sabis.Bolum.WebUI.Areas.Anket.Controllers
{
    public class DegerlendirmeController : Controller
    {
        // GET: Anket/Degerlendirme
        //TabloYok
        //public ActionResult Sonuc(int yil, int donem)
        //{
        //    Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc result = new Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc();
        //    result = Sabis.Bolum.Bll.SOURCE.ABS.ANKET.AnketDegerlendirme.GetirDegerlendirmeSonuc(yil, donem, Sabitler.KullaniciID);
        //    ViewBag.LayoutAc = true;
        //    return View(result);
        //}

        //public ActionResult BireyselSonuc(int personelID)
        //{
        //    Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc result = new Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc();
        //    ViewBag.LayoutAc = false;
        //    if (personelID != 0)
        //    {
        //        result = Sabis.Bolum.Bll.SOURCE.ABS.ANKET.AnketDegerlendirme.GetirDegerlendirmeSonuc(Sabitler.Yil, Sabitler.Donem, personelID);
        //    }

        //    return View("Index", result);
        //}

        //public ActionResult Genel()
        //{
        //    var result = Sabis.Bolum.Bll.SOURCE.ABS.ANKET.AnketDegerlendirme.GenelDegerlendirmeSonuc(Sabitler.Yil, Sabitler.Donem);

        //    return View(result);
        //}

        //public ActionResult Genel2()
        //{
        //    var result = Sabis.Bolum.Bll.SOURCE.ABS.ANKET.AnketDegerlendirme.GenelDegerlendirmeSonuc2(Sabitler.Yil, Sabitler.Donem).OrderByDescending(x => x.GenelToplam).ToList();

        //    return View(result);
        //}
    }
}

WEBUI/Areas/Ders/Controllers/DegerlendirmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Sabis.Bolum.Core.ABS.DEGERLENDIRME;
using System.Text;

namespace Sabis.Bolum.WebUI.Areas.Ders.Controllers
{
    //[AllowAnonymous]
    public class DegerlendirmeController : Controller
    {
        public ActionResult Index(int ID, bool hiyerarsik = false)
        {
            DegerlendirmeViewModel result = null;
            if (hiyerarsik)
            {
                result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.GetirDegerlendirme(ID, true, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi, Sabitler.Yil, Sabitler.DegerlendirmeDonem);
            }
            else
            {
                ViewBag.DersGrupID = Sabitler.GetirDersDetay(ID).DersGrupID;
                result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.GetirDegerlendirme(Sabitler.GetirDersDetay(ID).DersGrupID, false, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi, Sabitler.Yil, Sabitler.DegerlendirmeDonem);
            }

            if (result.DegerlendirmeCikti != null)
            {
                VeriHazirla(result.DegerlendirmeCikti.IstatistikMutlak, result.DegerlendirmeCikti.IstatistikBagil);
            }

            if (result.OrtakGruplar == null)
            {
                result.OrtakGruplar = new List<Grup>();
            }

            if (result.DegerlendirmeCikti == null)
            {
                result.DegerlendirmeCikti = new CiktiDTO();
                result.DegerlendirmeCikti.NotList = new List<OgrNot>();
            }

            result.IslemID = 0;
            if (result.Ders == null)
            {
                result.Ders = new DersDTO();
            }
            else
            {
                result.IslemID = result.Ders.Hiyerarsik ? result.Ders.DersPlanAnaID : result.Ders.DersGrupID.Value;
            }

#if DEBUG
            result.SonHalKaldirmaYetkisiVarMi = true;
#endif

            return View(result);
        }

        [HttpPost]
        public JsonResult Hesapla(int ID, string bagil, string ust, bool hiyerarsik = false)
        {
            bagil = bagil.Replace('.', ',');
            ust = ust.Replace('.', ',');
            double bagilOrtalama = double.Parse(bagil);
            double ustSinir = double.Parse(ust);

            DegerlendirmeViewModel result = new DegerlendirmeViewModel();
            if (hiyerarsik)
            {
                result.NotificationList = new List<Notification>();
                try
                {
                    Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim hdeg = new Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim(ID, Sabitler.Yil, Sabitler.DegerlendirmeDonem, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi);
                    hdeg.Degerlendir(default(double?));
                    hdeg.Kaydet();
                    result.DegerlendirmeCikti = hdeg.DegerlendirmeSonuc;
                    result.Ders = hdeg.SeciliDers;
                    result.AkademikTakvim = hdeg.AkademikTakvim;
                    result.NotificationList = hdeg.NotificationList;
                    result.EnumDegerlendirmeAsama = hdeg.EnumDegerlendirmeAsama;
                    result.SonHalKaldirmaYetkisiVarMi = hdeg.SonHalKaldirmaYetkisiVarMi;
                }
                catch (Exception ex)
                {
                    result.NotificationList.Add(new Notification("HATA", ex.Message, Notification.MasterMesajTip.Hata));
                }

            }
            else
            {
                result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.Hesapla(bagilOrtalama, ustSinir, ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            }
            return Json(result.NotificationList);
        }

        [HttpPost]
        public JsonResult Sifirla(int ID, bool hiyerarsik = false)
        {
            DegerlendirmeViewModel result = new DegerlendirmeViewModel();
            if (hiyerarsik)
            {
                result.NotificationList = new List<Notification>();
                try
                {
                    Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim hdeg = new Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim(ID, Sabitler.Yil, Sabitler.DegerlendirmeDonem, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi);
                    hdeg.Sifirla();
                    result.DegerlendirmeCikti = hdeg.DegerlendirmeSonuc;
                    result.Ders = hdeg.SeciliDers;
                    result.AkademikTakvim = hdeg.AkademikTakvim;
                    result.NotificationList = hdeg.NotificationList;
                    result.EnumDegerlendirmeAsama = hdeg.EnumDegerlendirmeAsama;
                    result.SonHalKaldirmaYetkisiVarMi = hdeg.SonHalKaldirmaYetkisiVarMi;
                }
                catch (Exception ex)
                {
                    result.NotificationList.Add(new Notification("HATA", ex.Message, Notification.MasterMesajTip.Hata));
                }

            }
            else
            {
                result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.Sifirla(ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            }
            return Json(result.NotificationList);
        }

        [HttpPost]
        public JsonResult SonHal(int ID, bool hiyerarsik = false)
        {
            DegerlendirmeViewModel result = new DegerlendirmeViewModel();
            if (hiyerarsik)
            {
                result.NotificationList = new List<Notification>();
                try
                {
                    Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim hdeg = new Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim(ID, Sabitler.Yil, Sabitler.DegerlendirmeDonem, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi);
                    hdeg.Yayinla();
                    hdeg.SonHal();
                    result.DegerlendirmeCikti = hdeg.DegerlendirmeSonuc;
                    result.Ders = hdeg.SeciliDers;
                    result.AkademikTakvim = hdeg.AkademikTakvim;
                    result.NotificationList = hdeg.NotificationList;
                    result.EnumDegerlendirmeAsama = hdeg.EnumDegerlendirmeAsama;
                    result.SonHalKaldirmaYetkisiVarMi = hdeg.SonHalKaldirmaYetkisiVarMi;
                }
                catch (Exception ex)
                {
                    result.NotificationList.Add(new Notification("HATA", ex.Message, Notification.MasterMesajTip.Hata));
                }
            }
            else
            {
                result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.SonHal(ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            }

            return Json(result.NotificationList);
        }

        [HttpPost]
        public JsonResult SonHalSerbest(int ID)
        {
            var result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.SonHalSerbest(ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            return Json(result.NotificationList);
        }

        [HttpPost]
        public JsonResult SonHalKaldir(int ID, bool hiyerarsik = false)
        {
            DegerlendirmeViewModel result = new DegerlendirmeViewModel();
            if (hiyerarsik)
            {
                result.NotificationList = new List<Notification>();
                try
                {
                    Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim hdeg = new Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.HDegerlendirmeYonetim(ID, Sabitler.Yil, Sabitler.DegerlendirmeDonem, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi);
                    hdeg.SonHalKaldir();
                    result.DegerlendirmeCikti = hdeg.DegerlendirmeSonuc;
                    result.Ders = hdeg.SeciliDers;
                    result.AkademikTakvim = hdeg.AkademikTakvim;
                    result.NotificationList = hdeg.NotificationList;
                    result.EnumDegerlendirmeAsama = hdeg.EnumDegerlendirmeAsama;
                    result.SonHalKaldirmaYetkisiVarMi = hdeg.SonHalKaldirmaYetkisiVarMi;
                }
                catch (Exception ex)
                {
                    result.NotificationList.Add(new Notification("HATA", ex.Message, Notification.MasterMesajTip.Hata));
                }
            }
            else
            {
                result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.SonHalKaldir(ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            }
            return Json(result.NotificationList);
        }

        [HttpPost]
        public JsonResult SonHalKaldirSerbest(int ID)
        {
            var result = Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.SonHalKaldirSerbest(ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            Sabis.Bolum.Bll.SOURCE.ABS.DEGERLENDIRME.DegerlendirmeBL.YayindanKaldirSerbest(ID, Sabitler.KullaniciAdi, Sabitler.KullaniciID, Sabitler.IPAdresi, Sabitler.SimulasyonKullaniciAdi);
            return Json(result.NotificationList);
        }

        [HttpPost]
        public JsonResult Yayinla(int ID, bool hiyerarsik = false)
        {
            DegerlendirmeViewModel result = new DegerlendirmeViewModel();
            if (hiyerarsik)
            {
                result.NotificationList = new List<Notification>();
                try
                {

WEBUI/Areas/Anket/Views/Degerlendirme/Genel.cshtml
@model Sabis.Bolum.Core.ABS.ANKET.GenelDegerlendirme

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Navigation
{
    <div class="col-md-9">
        <ul class="page-breadcrumb breadcrumb" style="padding-top:10px;">
            <li><a href="http://abs.apollo.gtu.edu.tr">APOLLO</a><i class="fa fa-chevron-right"></i></li>
            <li><a href='/'>Akademik Bilgi Sistemi</a><i class="fa fa-chevron-right"></i></li>
            <li>Sonuç Birim</li>
        </ul>
    </div>
}
<div class="panel panel-green" id="genel">
    <div class="panel-heading">
        <h4>Genel Değerlendirme</h4>
    </div>
    <div class="panel-body">
        <div class="row text-right">
            <div class="btn-group ">
                <a href="#" class="btn btn-default-alt">Fakülteler</a>
                <a href="#" class="btn btn-default-alt dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                <ul class="dropdown-menu anchorListUst" role="menu"></ul>
            </div>
        </div>


        @foreach (var item in Model.BirimSonucList.OrderBy(x => x.Value.BirimAd))
        {
            <div class="well well-lg fakulte">
                <h4 name="@item.Value.BirimAd" id="anchor-@item.Value.BirimID">@item.Value.BirimAd</h4>
                <div class="row text-right">
                    <div class="btn-group " style="background:#fff;">
                        <a href="#" class="btn btn-default-alt">Bölümler</a>
                        <a href="#" class="btn btn-default-alt dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                        <ul class="dropdown-menu anchorList" role="menu"></ul>
                    </div>
                    <br />
                </div>

                @if (item.Value.BirimSonucList != null)
                {
                    @Html.Partial("_Birim", item.Value.BirimSonucList.OrderBy(x=>x.Value.BirimAd).ToDictionary(x=> x.Key, x=> x.Value))
                }
                else
                {
                    if (item.Value.PersonelList != null)
                    {
                        @Html.Partial("_Personel", item.Value.PersonelList)
                    }
                }
            </div>
        }
    </div>
</div>

<div id="personel">

</div>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/linq.js/2.2.0.2/jquery.linq.min.js"></script>
@*<script src="~/assets/js/jquery.blockUI.min.js"></script>*@
<script type="text/javascript">

    function getSorted(selector, attrName) {
        return $($(selector).toArray().sort(function (a, b) {
            var aVal = parseInt(a.getAttribute(attrName)),
                bVal = parseInt(b.getAttribute(attrName));
            return aVal - bVal;
        }));
    }

    $(function () {

        $.blockUI("Lütfen Bekleyiniz..");

        //var list1 = [];

        $('strong[id^="anchor-"]').each(function (i, item) {
            //var data = {
            //    id: $(this).attr('id'),
            //    text: $(this).text()
            //};
            //list1.push(data);
            $(this).closest('.fakulte').find(".anchorList").append($('<li>').append($('<a href="#' + $(this).attr('id') + '">').append($(this).text())));
        });


        //var list2 = [];

        $('h4[id^="anchor-"]').each(function (i, item) {
            //var data = {
            //    id: $(this).attr('id'),
            //    text: $(this).text()
            //};
            //list2.push(data);
            $(this).closest('.panel-body').find(".anchorListUst").append($('<li>').append($('<a href="#' + $(this).attr('id') + '">').append($(this).text())));
        });

        //list2 = list2.sort(function (a, b) { return (a.text > b.text) ? 1 : ((b.text > a.text) ? -1 : 0); })
        //$.each(list2, function (i, obj) {
        //    $(this).closest('.panel-body').find(".anchorListUst").append($('<li>').append($('<a href="#' + obj.id + '">').append(obj.text)));
        //});

        $.unblockUI();

    });


    function personelGetir(personelID) {
        $("#genel").hide();
        $("#personel").load('@Url.Action("BireyselSonuc","Degerlendirme")', { personelID: personelID });
    }

    function geneleGit() {
        $("#personel").empty();
        $("#genel").show();
    }
</script>

WEBUI/Areas/Anket/Views/Degerlendirme/Genel2.cshtml
@model List<Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Navigation
{
    <div class="col-md-9">
        <ul class="page-breadcrumb breadcrumb" style="padding-top:10px;">
            <li><a href="http://abs.apollo.gtu.edu.tr">APOLLO</a><i class="fa fa-chevron-right"></i></li>
            <li><a href='/'>Akademik Bilgi Sistemi</a><i class="fa fa-chevron-right"></i></li>
            <li>Sonuç Sıralı</li>
        </ul>
    </div>
}
<div class="panel panel-green" id="genel">
    <div class="panel-heading">
        <h4>Genel Değerlendirme</h4>
    </div>
    <div class="panel-body">
        @Html.Partial("_Personel", Model)
    </div>
</div>

<div id="personel">

</div>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/linq.js/2.2.0.2/jquery.linq.min.js"></script>
@*<script src="~/assets/js/jquery.blockUI.min.js"></script>*@
<script type="text/javascript">

    function getSorted(selector, attrName) {
        return $($(selector).toArray().sort(function (a, b) {
            var aVal = parseInt(a.getAttribute(attrName)),
                bVal = parseInt(b.getAttribute(attrName));
            return aVal - bVal;
        }));
    }

    $(function () {

        $.blockUI("Lütfen Bekleyiniz..");

        //var list1 = [];

        $('strong[id^="anchor-"]').each(function (i, item) {
            //var data = {
            //    id: $(this).attr('id'),
            //    text: $(this).text()
            //};
            //list1.push(data);
            $(this).closest('.fakulte').find(".anchorList").append($('<li>').append($('<a href="#' + $(this).attr('id') + '">').append($(this).text())));
        });


        //var list2 = [];

        $('h4[id^="anchor-"]').each(function (i, item) {
            //var data = {
            //    id: $(this).attr('id'),
            //    text: $(this).text()
            //};
            //list2.push(data);
            $(this).closest('.panel-body').find(".anchorListUst").append($('<li>').append($('<a href="#' + $(this).attr('id') + '">').append($(this).text())));
        });

        //list2 = list2.sort(function (a, b) { return (a.text > b.text) ? 1 : ((b.text > a.text) ? -1 : 0); })
        //$.each(list2, function (i, obj) {
        //    $(this).closest('.panel-body').find(".anchorListUst").append($('<li>').append($('<a href="#' + obj.id + '">').append(obj.text)));
        //});

        $.unblockUI();

    });


    function personelGetir(personelID) {
        $("#genel").hide();
        $("#personel").load('@Url.Action("BireyselSonuc","Degerlendirme")', { personelID: personelID });
    }

    function geneleGit() {
        $("#personel").empty();
        $("#genel").show();
    }
</script>

WEBUI/Areas/Anket/Views/Degerlendirme/Sonuc.cshtml
@model Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc

@if (ViewBag.LayoutAc)
{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
else
{
    Layout = null;
}
@section Navigation
{
    <div class="col-md-9">
        <ul class="page-breadcrumb breadcrumb" style="padding-top:10px;">
            <li><a href="http://abs.apollo.gtu.edu.tr">APOLLO</a><i class="fa fa-chevron-right"></i></li>
            <li><a href='/'>Akademik Bilgi Sistemi</a><i class="fa fa-chevron-right"></i></li>
            <li>Bireysel Sonuç</li>
        </ul>
    </div>
}

<div class="btn-group pull-right btn-sm-block btn-xs-block">
    <a class="btn default btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">YIL ve DÖNEM</a>
    <ul class="dropdown-menu pull-right">
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2017&donem=1" data-yil="2017" data-donem="1">2017 - 2018 Güz Dönemi</a></li>
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2016&donem=3" data-yil="2016" data-donem="3">2016 - 2017 Yaz Dönemi</a></li>
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2016&donem=2" data-yil="2016" data-donem="2">2016 - 2017 Bahar Dönemi</a></li>
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2016&donem=1" data-yil="2016" data-donem="1">2016 - 2017 Güz Dönemi</a></li>
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2015&donem=3" data-yil="2015" data-donem="3">2015 - 2016 Yaz Dönemi</a></li>
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2015&donem=2" data-yil="2015" data-donem="2">2015 - 2016 Bahar Dönemi</a></li>
        <li><a href="/Anket/Degerlendirme/Sonuc?yil=2015&donem=1" data-yil="2015" data-donem="1">2015 - 2016 Güz Dönemi</a></li>
    </ul>
</div>


<div class="panel panel-sky">
    <div class="panel-heading">
        <h4>@Model.AdSoyadUnvan</h4>
    </div>
    <div class="panel-body">
        <button type="button" onclick="geneleGit()" class="btn btn-danger pull-right">Geri</button>
        <h4>Genel Değerlendirme: @Model.GenelToplam</h4>

        <div class="well well-lg">
            <h4>Personel Değerlendirme Sonuçları</h4>
            <div class="row">
                <table class="table table-condensed table-striped table-bordered" style="background:#fff;">
                    <thead>
                        <tr>
                            <th>
                                No
                            </th>
                            <th>
                                Metin
                            </th>
                            <th>
                                Adet
                            </th>
                            <th>
                                Puan
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var personelSoru in Model.PersonelDegerlendirme.SoruCevapList)
                        {
                            <tr>
                                <td>
                                    @personelSoru.SoruNo
                                </td>
                                <td>
                                    @personelSoru.SoruMetin
                                </td>
                                <td>
                                    @personelSoru.Adet
                                </td>
                                <td>
                                    @personelSoru.Puan
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3" class="text-right">
                                Toplam:
                            </td>
                            <td>
                                @Model.PersonelDegerlendirme.GenelToplam
                            </td>
                        </tr>
                    </tfoot>
                </table>

            </div>
        </div>



        @foreach (var ders in Model.DersDegerlendirmeList)
        {
            <div class="well well-sm">


                <h4>@ders.DersAd</h4>
                <div class="row">
                    <h5>Öğrenci Anket Sonuçları</h5>
                    <table class="table table-condensed table-striped table-bordered" style="background:#fff;">
                        <thead>
                            <tr>
                                <th>
                                    No
                                </th>
                                <th>
                                    Metin
                                </th>
                                <th>
                                    Adet
                                </th>
                                <th>
                                    Puan
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var ogrenciSoru in ders.SoruCevapList)
                            {
                                <tr>
                                    <td>
                                        @ogrenciSoru.SoruNo
                                    </td>
                                    <td>
                                        @ogrenciSoru.SoruMetin
                                    </td>
                                    <td>
                                        @ogrenciSoru.Adet
                                    </td>
                                    <td>
                                        @ogrenciSoru.Puan
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3" class="text-right">
                                    Toplam:
                                </td>
                                <td>
                                    @ders.SoruCevapToplam
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                    <h5>Döküman Sonuçları</h5>
                    <table class="table table-condensed table-striped table-bordered" style="background:#fff;">
                        <thead>
                            <tr>
                                <th>
                                    Tip
                                </th>
                                <th>
                                    Adet
                                </th>
                                <th>
                                    Puan
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var dokuman in ders.DokumanList)
                            {
                                <tr>
                                    <td>
                                        @dokuman.DokumanTipi
                                    </td>
                                    <td>
                                        @dokuman.Adet
                                    </td>
                                    <td>
                                        @dokuman.Puan
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="2" class="text-right">
                                    Toplam:
                                </td>
                                <td>
                                    @ders.DokumanToplam
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        }


    </div>
</div>

WEBUI/Areas/Anket/Views/Degerlendirme/_Birim.cshtml
@model Dictionary<int, Sabis.Bolum.Core.ABS.ANKET.BirimSonuc>

@{
    Layout = null;
}

@foreach (var item in Model)
{
    <div class="well well-lg">
        <strong data-ad="@item.Value.BirimAd" id="anchor-@item.Value.BirimID">@item.Value.BirimAd</strong>
        <a href="#genel" class="pull-right">Yukarı Git</a>
        @if (item.Value.BirimSonucList != null)
        {
            @Html.Partial("_Birim", item.Value.BirimSonucList)
        }
        else
        {
            if (item.Value.PersonelList != null)
            {
                @Html.Partial("_Personel", item.Value.PersonelList)
            }
        }
    </div>
}

WEBUI/Areas/Anket/Views/Degerlendirme/_Personel.cshtml
@model List<Sabis.Bolum.Core.ABS.ANKET.DegerlendirmeSonuc>

@{
    Layout = null;
}

<table class="table table-condensed  table-bordered" style="background-color:#fff;">
    <thead>
        <tr>
            <th>
                Foto
            </th>
            <th>
                Ünvan Ad Soyad
            </th>
            <th>
                Birim
            </th>
            <th>
                Genel Toplam
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var personel in Model)
        {
            <tr>
                <td class="text-center">
                    <img src="@FotografClient.Client.FotografGetir(personel.KullaniciAdi)" height="80" style="cursor:pointer;" onclick="personelGetir(@personel.PersonelID);" />
                </td>
                <td>
                    @personel.AdSoyadUnvan
                </td>
                <td>
                    @personel.BirimAd
                </td>
                <td>
                    @personel.GenelToplam
                </td>
            </tr>
        }
    </tbody>
</table>